### ISSUE TITLE
could not find the import-settings.txt

### ISSUE THREAD

**Issue by cat2tom** [cutright/DVH-Analytics-Bokeh#18]
Hi Cutright,
Thanks a lot for developing this great tools. When I setup and try to run the main.py, the following errors occurred. Could you help me to resolve this? Thanks.

tom

File "C:\AitangResearch\DVHAnalytics\dvh\main.py", line 50, in <module>
  temp_dvh_info = Temp_DICOM_FileSet()
File "C:\AitangResearch\DVHAnalytics\dvh\utilities.py", line 31, in __init__
  with open(abs_file_path, 'r') as document:

IOError: [Errno 2] No such file or directory: 'C:\\AitangResearch\\DVHAnalytics\\dvh\\preferences/import_settings.txt'

**Comment by cutright** [comment]
Hi Tom, thanks for checking this out.

Prior to running main.py, you'll need to run settings.py from the same directory as main.py
`$ bokeh serve settings.py --show`
This should start a very simple Bokeh server as shown below.

<img width="519" alt="settings" src="https://user-images.githubusercontent.com/4778878/31647315-14769314-b2cd-11e7-877a-d6a1c5edac2e.png">

I wrote my installation notes assuming a PyPI installation, but I'll work on more a convenient installation when cloning the code instead of using pip install (which I'm assuming you've done).  Please don't hesitate to reach out with any other questions.  As far as I know, you're the first to use this outside of my colleagues on the project.

**Comment by cutright** [comment]
Hi Tom,

I've added a start.py file in the same directory as main.py.  This is simply a copy of \_\_main__.py, so it functions the same but you can run start.py as a main without the PyPI installation.

If you follow the instructions at:
https://github.com/cutright/DVH-Analytics/blob/master/install_notes.md

Anytime it says something like
`$ dvh settings`
replace `dvh` with `python start.py` (assuming you're runnings from the dvh/ directory, like so
`$ python start.py settings`

Now, if you try to run the main or admin bokeh servers without having this settings file in place, you'll be prompted to create it.

This is my first python project, so if there is a more eloquent solution, I'm happy to adapt the code.
