### ISSUE TITLE
I am having issue with the mlc_analyzer

### ISSUE THREAD

**Issue by sabodunde** [cutright/DVH-Analytics-Bokeh#27]
Error:
```
AttributeErrorTraceback (most recent call last)
<ipython-input-42-a660279469d7> in <module>()

from dvh import mlc_analyzer as mlca
----> 1 pcs = mlca.Plan(rtplan1_dcm)

C:\AppData\Local\conda\conda\envs\mppy27\lib\site-packages\dvh\mlc_analyzer.pyc in __init__(self, rt_plan)
     16 class Plan:
     17     def __init__(self, rt_plan):
---> 18         self.fx_group = [FxGroup(fx_grp_seq, rt_plan.BeamSequence) for fx_grp_seq in rt_plan.FractionGroupSequence]

AttributeError: 'str' object has no attribute 'FractionGroupSequence'
```
Although rtplan.ds.FractionGroupSequence does exist.
Please, how do i get around this.
Thank you.

**Comment by cutright** [comment]
Interesting... which TPS are you using?

**Comment by cutright** [comment]
It looks like the version you have is missing the line:
`rt_plan = dicomparser.read_file(rt_plan_file)`

My original version read a pydicom object, but I've since changed the input to absolute file path and handle the parsing for you.  Perhaps that's what happened?  Sorry for the change up... but happy to see someone using this code so quickly.

The latest version in PyPI and Github should look like this:
https://github.com/cutright/DVH-Analytics/blob/bf6bf5a26685cad576f615c462bf9a78cf40126a/dvh/mlc_analyzer.py#L16-L23

**Comment by cutright** [comment]
I'm pretty sure this should have resolved your issues, if not please feel free to add more comments and I'll reopen the issue.
